name: weather_hybrid_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.2
  flutter_map: ^4.0.0
  google_maps_flutter: ^2.1.1  # Add this line for Google Maps
  latlong2: ^0.8.1
  shared_preferences: ^2.2.2
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11
  firebase_auth: ^5.6.2
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  assets:
  #- .env - remove for netlify but uncomment for local dev
  - assets/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
  adaptive_icon_background: "#1976D2"
  adaptive_icon_foreground: "assets/logo.png"
